version: '3.8'

services: 
  part2-mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: part2-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - part2-mongodb-data:/data/db
    restart: unless-stopped

  part1-mysql:
    image: mariadb
    container_name: part1-mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - part1-mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  part2-mongodb-data:
  part1-mysql-data:
