// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_adventure_genre_roles from "./routes/api/adventure_genre_roles.tsx";
import * as $api_genre_country_view from "./routes/api/genre_country_view.tsx";
import * as $api_highest_avg_score from "./routes/api/highest_avg_score.tsx";
import * as $index from "./routes/index.tsx";
import * as $AdventureGenreRolesModal from "./islands/AdventureGenreRolesModal.tsx";
import * as $GenreCountryViewModal from "./islands/GenreCountryViewModal.tsx";
import * as $HighestAvgScoreModal from "./islands/HighestAvgScoreModal.tsx";
import * as $ModalButton from "./islands/ModalButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/adventure_genre_roles.tsx": $api_adventure_genre_roles,
    "./routes/api/genre_country_view.tsx": $api_genre_country_view,
    "./routes/api/highest_avg_score.tsx": $api_highest_avg_score,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AdventureGenreRolesModal.tsx": $AdventureGenreRolesModal,
    "./islands/GenreCountryViewModal.tsx": $GenreCountryViewModal,
    "./islands/HighestAvgScoreModal.tsx": $HighestAvgScoreModal,
    "./islands/ModalButton.tsx": $ModalButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
