cargo-features = ["edition2024"]

[package]
name = "src-lib"
version = "0.1.0"
edition = "2024"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true
